export type LessonStyle = "stationary" | "horizontal" | "blackgray";

export interface LessonConfig {
  id: number;
  name: string;
  group: string;
  style: LessonStyle;
  showBackground: boolean;    // blue highlight background
  showSurrounding: boolean;   // show adjacent phrases in gray
  reducedFontSize: boolean;
  doublePass: boolean;        // auto + manual (lessons 4, 8, 12)
  focusDots: boolean;         // lesson 10
  allowWrap: boolean;         // lessons 11, 12
  measureConcentration: boolean; // 1-8
  description: string;
}

export const LESSONS: LessonConfig[] = [
  {
    id: 1,
    name: "Lesson 1",
    group: "Stationary Phrase",
    style: "stationary",
    showBackground: true,
    showSurrounding: false,
    reducedFontSize: false,
    doublePass: false,
    focusDots: false,
    allowWrap: false,
    measureConcentration: true,
    description: "Each phrase on its own, large font, blue background.",
  },
  {
    id: 2,
    name: "Lesson 2",
    group: "Stationary Phrase",
    style: "stationary",
    showBackground: false,
    showSurrounding: false,
    reducedFontSize: true,
    doublePass: false,
    focusDots: false,
    allowWrap: false,
    measureConcentration: true,
    description: "No blue background, slightly smaller text.",
  },
  {
    id: 3,
    name: "Lesson 3",
    group: "Stationary Phrase",
    style: "stationary",
    showBackground: false,
    showSurrounding: true,
    reducedFontSize: true,
    doublePass: false,
    focusDots: false,
    allowWrap: false,
    measureConcentration: true,
    description: "Surrounding phrases shown in light gray.",
  },
  {
    id: 4,
    name: "Lesson 4",
    group: "Stationary Phrase",
    style: "stationary",
    showBackground: false,
    showSurrounding: true,
    reducedFontSize: true,
    doublePass: true,
    focusDots: false,
    allowWrap: false,
    measureConcentration: true,
    description: "Double pass — auto at 20% above avg, then manual.",
  },
  {
    id: 5,
    name: "Lesson 5",
    group: "Horizontal Scanning",
    style: "horizontal",
    showBackground: true,
    showSurrounding: false,
    reducedFontSize: false,
    doublePass: false,
    focusDots: false,
    allowWrap: false,
    measureConcentration: true,
    description: "Phrases highlighted with blue background, side-to-side scan.",
  },
  {
    id: 6,
    name: "Lesson 6",
    group: "Horizontal Scanning",
    style: "horizontal",
    showBackground: false,
    showSurrounding: false,
    reducedFontSize: true,
    doublePass: false,
    focusDots: false,
    allowWrap: false,
    measureConcentration: true,
    description: "No blue background, smaller text.",
  },
  {
    id: 7,
    name: "Lesson 7",
    group: "Horizontal Scanning",
    style: "horizontal",
    showBackground: false,
    showSurrounding: false,
    reducedFontSize: true,
    doublePass: false,
    focusDots: false,
    allowWrap: false,
    measureConcentration: true,
    description: "Further reduced font size.",
  },
  {
    id: 8,
    name: "Lesson 8",
    group: "Horizontal Scanning",
    style: "horizontal",
    showBackground: false,
    showSurrounding: false,
    reducedFontSize: true,
    doublePass: true,
    focusDots: false,
    allowWrap: false,
    measureConcentration: true,
    description: "Double pass — auto at 20% above avg, then manual.",
  },
  {
    id: 9,
    name: "Lesson 9",
    group: "Black & Gray",
    style: "blackgray",
    showBackground: false,
    showSurrounding: false,
    reducedFontSize: false,
    doublePass: false,
    focusDots: false,
    allowWrap: false,
    measureConcentration: false,
    description: "Alternating black & gray text, no highlight.",
  },
  {
    id: 10,
    name: "Lesson 10",
    group: "Black & Gray",
    style: "blackgray",
    showBackground: false,
    showSurrounding: false,
    reducedFontSize: false,
    doublePass: false,
    focusDots: true,
    allowWrap: false,
    measureConcentration: false,
    description: "Focus Dots© guide eyes for peripheral reading.",
  },
  {
    id: 11,
    name: "Lesson 11",
    group: "Black & Gray",
    style: "blackgray",
    showBackground: false,
    showSurrounding: false,
    reducedFontSize: false,
    doublePass: false,
    focusDots: false,
    allowWrap: true,
    measureConcentration: false,
    description: "Phrases may wrap between lines.",
  },
  {
    id: 12,
    name: "Lesson 12",
    group: "Black & Gray",
    style: "blackgray",
    showBackground: false,
    showSurrounding: false,
    reducedFontSize: false,
    doublePass: true,
    focusDots: false,
    allowWrap: true,
    measureConcentration: false,
    description: "Double pass — auto at 20% above avg, then manual.",
  },
];

export const LESSON_GROUPS = [
  { name: "Stationary Phrase", ids: [1, 2, 3, 4], description: "Lessons 1–4" },
  { name: "Horizontal Scanning", ids: [5, 6, 7, 8], description: "Lessons 5–8" },
  { name: "Black & Gray", ids: [9, 10, 11, 12], description: "Lessons 9–12" },
];
